### ISSUE TITLE
This PrefPane is brilliant and feedback

### ISSUE THREAD

**Issue by edrozenberg** [MaccaTech/PostgresPrefs#10]
Works really well, even picks up several pgsql instances if there are for example both a HomeBrew installation and a Postgres.app installation.

A few notes:
- I cannot rename the homebrew server entry (shows a lock icon, I assume it cannot be renamed)
- "Change Settings" and "Startup" options are disabled, I assume it's because they cannot be changed for the homebrew installation. I did enter my sudo password but they remain greyed out.
- Nice to have the View Log button!

Thanks!

**Comment by mckenfra** [comment]
Thanks a lot for the feedback. I worked really hard on it, and it's not always easy to know if people find it useful, so nice to receive a positive response :)

Re. your points - the preference pane is designed not to modify files it doesn't own, e.g. the configuration files created by Homebrew / Postgresapp.

What you can do is to select the Homebrew server in the list, then click the gear icon and select "Duplicate". This will create a copy of the Homebrew configuration file, and with this copy you can then edit the settings and change the startup.

If you want, you can click the '-' button to delete the original, locked Homebrew server configuration. It will ask you if you want to delete the underlying configuration file (originally created by the Homebrew installation). You can go ahead and allow the preference pane to delete it, or you can manually delete/rename/move it yourself by clicking on "Show in Finder".

**Comment by tkrajacic** [comment]
+1 on the positive feedback!
You have created something truly useful and great!

**Comment by mckenfra** [comment]
Thanks, glad it's useful :)

**Comment by edrozenberg** [comment]
Thanks a lot for the tips on duplicating an existing configuration! Out of curiosity I made a duplicate to see the results.

Existing service control file:

    ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

New service control file it created:

    ~/Library/LaunchAgents/org.postgresql.preferences.Postgresql New.plist

I noticed some differences between the last sections in the two files so it is not making a "perfect" duplicate.

Original file:

````
  <key>WorkingDirectory</key>
  <string>/usr/local</string>
  <key>StandardErrorPath</key>
  <string>/usr/local/var/lib/postgres/server.log</string>
````

New file:
````
	<key>StandardErrorPath</key>
	<string>/Users/eduardr/Library/Logs/PostgreSQL/org.postgresql.preferences.Postgresql New.log</string>
	<key>StandardOutPath</key>
	<string>/Users/eduardr/Library/Logs/PostgreSQL/org.postgresql.preferences.Postgresql New.log</string>
	<key>WorkingDirectory</key>
	<string>/usr/local/var/lib/postgres</string>
````

There is a new stdout path (not present in the homebrew service control file) and the stderr is set to a different location (/Users/eduardr/Library/Logs/PostgreSQL) which is not present on my machine. Maybe it would work, not sure, perhaps it is assuming a Postgres.app setup instead of homebrew.

Regards,
--Ed

**Comment by mckenfra** [comment]
Thanks for testing and taking the time to post these results. I'll need to have a look into this and consider a bit. I'm just travelling at the moment, but will have a look when I get a chance.

The preference pane in general tries to standardise where logging goes - don't worry, it will automatically create `/Users/eduardr/Library/Logs/PostgreSQL` when you start postgresql using the preference pane.

But if you explicitly specify a log file, it *should* use this instead of its default.

Note that the preference pane detects existing postgresql instances (e.g. Homebrew) by looking up running processes in launchd. However, the information launchd provides for running processes is not always as complete as the information stored in the .plist file used to launch the process. But I thought I had included some code to scan for a matching .plist file when a postgresql server is detected in launchd. I'll need to check this.

I'll need to do a bit of investigating about the WorkingDirectory, as I'm not sure exactly how it affects postgresql. I hadn't thought it was an important setting, so just put in some code to guess a default value. But I may need to make it check a bit more carefully if it is an important setting.

So one question for you: if you start Homebrew using `Postgresql New` in the preference pane instead of the homebrew file, does it still work ok? Is it only the log file location that is affected?

**Comment by mckenfra** [comment]
On further consideration, and re-reading your comment, I think there are no problems with the current implementation.

You mention that log directory `/Users/eduardr/Library/Logs/PostgreSQL` doesn't exist, but this will be automatically created when you click `Start PostgreSQL`. It is an intentional feature of the preference pane - i.e. to provide a standard location for log files.

As for the working directory query, I cannot find any issues with this. So unless you have any further comments, I will close this issue. Thanks again for your feedback!
