### ISSUE TITLE
Startup options are greyed out

### ISSUE THREAD

**Issue by shatfield** [MaccaTech/PostgresPrefs#13]
I just installed this on Mojave and it starts/stops PostgreSQL just fine. The problem is that the "Startup" options (Manual, At Boot, At Login) are disabled, even if I unlock the pref pane. The "Change Settings" button is also disabled.

NOTE:
PostgreSQL was installed by following the instructions at  https://www.moncefbelyamani.com/how-to-install-postgresql-on-a-mac-with-homebrew-and-lunchy/

**Comment by mckenfra** [comment]
Thanks for taking the time to report this. I'll have a look and get back to you.
Francis

**Comment by mckenfra** [comment]
Hi, actually this is going to be tricky for me to debug, because I don't have Mojave on any of my devices and can't risk upgrading at the moment!

Have you tried clicking the "+" button at the bottom of the DATABASE SERVERS panel on the left-hand side?

**Comment by shatfield** [comment]
Thank you for checking on this. I am happy to help debug it if I can.

When I click the + button, it creates a 2nd server, and I can set its startup options, but they are disabled for the 1st server that was created when I installed the pref pane.

**Comment by mckenfra** [comment]
Yes, that's intended behaviour. Postgres Prefs can detect existing configuration files (and already-running servers) but will not modify them. So go ahead and configure the 2nd server to match the 1st. The easiest way to do this is to click on the 1st server, then click the gear icon at the bottom of the DATABASE SERVERS box, and select ```Duplicate Server```.

FYI - the 1st server was detected because you performed the following step (from your link):

```cp /usr/local/Cellar/postgresql/9.2.1/homebrew.mxcl.postgresql.plist ~/Library/LaunchAgents/```

So Postgres Prefs was able to find ```homebrew.mxcl.postgresql.plist```. But it doesn't want to modify it, because Postgres Prefs didn't create it. By clicking ```Duplicate Server``` above, you cause a copy of this plist file called ```org.postgresql.preferences.MyServer.plist``` to be created in the same directory.

After you've done this, you can select the 1st server again and click on the ```-``` button. You will see a popup giving you the option of deleting ```homebrew.mxcl.postgresql.plist```.

Does that make sense?

**Comment by shatfield** [comment]
Now the server will start at boot 👍 

Thanks for your help. I hope this helps someone else.

**Comment by mckenfra** [comment]
no problem!
