### ISSUE TITLE
Refuses to load on Catalina

### ISSUE THREAD

**Issue by BrianHawley** [MaccaTech/PostgresPrefs#14]
The preference pane refuses to load on macOS Catalina. The system refuses to load because the developer is unverified. When I go to Security and tell it to load anyway, it just says "Could not load PostgresSQL preference pane." - the error message that I'd expect if it's as 32bit.

Could you do a 64bit build? Verified if possible, but that's not strictly necessary because of the Security preference pane workaround.

**Comment by mckenfra** [comment]
Sure - I'm not on the latest MacOS version, though, so won't be able to test it. If I put up a new build can you let me know it runs ok?

**Comment by mckenfra** [comment]
Let me know if this works for you: https://github.com/MaccaTech/PostgresPrefs/releases/tag/v2.4.3

**Comment by s12chung** [comment]
the above version doesn't work for me on the latest Catalina. 2.4.2 works, but I can't stop the database.

**Comment by mckenfra** [comment]
Hi Steve - when you say 2.4.3 doesn't work, you mean it won't even start? It crashes?
With 2.4.2, you mean you can start the database, but not stop it?

**Comment by s12chung** [comment]
sorry, i should be more specific. it seems like it's unable to start or stop it on 2.4.2. the LaunchDaemon? is probably doing the work when I installed it ages ago. I get this when stopping:

![Screen Shot 2020-01-31 at 9 53 16 AM](https://user-images.githubusercontent.com/263394/73548957-af08a900-440f-11ea-8613-e3c9587a9aa2.png)

When the database is stopped, it just gets stuck on retrying.

For 2.4.3, I get:

![Screen Shot 2020-01-31 at 9 55 52 AM](https://user-images.githubusercontent.com/263394/73549076-e37c6500-440f-11ea-9ce2-bf674d00dcff.png)

![Screen Shot 2020-01-31 at 9 56 15 AM](https://user-images.githubusercontent.com/263394/73549099-f131ea80-440f-11ea-8fa4-1d8d518155a8.png)

Hope this helps. The security/permissions model changed quite a bit in Catalina.

**Comment by mckenfra** [comment]
Thanks Steve. After some research, I've learned that Catalina requires 3rd party apps outside the App Store to be notarized with Apple. It seems it's not possible to notarize a `.prefPane` file so I had to create a `.pkg` installer, and notarize that. The `.pkg` installer simply copies the contained `.prefPane` file to `/Library/PreferencePanes`.

Can you give it a try and let me know? You should probably uninstall `PostgresPrefs` first by opening `System Preferences`, right-clicking on the `PostgreSQL` icon and clicking `Remove`.

Then download `PostgreSQL.prefPane-v2.4.3.pkg` from the release page: https://github.com/MaccaTech/PostgresPrefs/releases/tag/v2.4.3 (be sure to choose the `.pkg` download, not the `.zip`) and double-click it to run the installer. Once installed, you'll need to restart `System Preferences` so that the `PostgreSQL` icon appears. Click on it, and assuming it now starts, try starting and stopping a server.

It's frustrating I can't test it myself, but I don't have Catalina and can't upgrade just at the moment!

**Comment by s12chung** [comment]
Now I'm getting the error from 2.4.2, `Not privileged to remove service`. Think I prefer the `zip` over the `.pkg` personally, as the `.pkg` requires the user to input their password/fingerprint.

**Comment by s12chung** [comment]
I get the feeling you're going to need to ask for permissions from macOS to access some directory. This is new in Catalina. https://www.howtogeek.com/443611/how-macos-catalinas-new-security-features-work/

**Comment by mckenfra** [comment]
Thanks Steve! Well that's good that Catalina at least allows 2.4.3 to run, using the notarized `.pkg` file. The reason it asks you for your password during install is because it is installing the `.prefPane` file to `/Library/PreferencePanes`, which is a system directory. I think I can change the installer to install instead to `~/Library/PreferencePanes`, which should avoid the need for a password (since it's in your home directory). Unfortunately, there's no way for me to notarize the `.zip` version. Apparently files built before some date in 2019 do not need to be notarized, but any new builds have to be. So while 2.4.2 will continue to at least run (since I built it _ages_ ago!), if I do a new build I must notarize it, otherwise it just won't run at all on Catalina. So I'll have to go with the `.pkg` format from now on. I agree the plain `.zip` seems simpler, but Apple is forcing the issue here.

Thanks for the hints about asking for permissions. To start/stop the PostgreSQL database, `PostgresPrefs` runs the following shell command: `launchctl load/remove <plist-filename>`. But the app _does_ ask the OS for a right called `kAuthorizationRightExecute` first - that's why you have to enter your password. Here's where I define the rights I need: https://github.com/MaccaTech/PostgresPrefs/blob/7ad2f9cecb33386a628f90ef3930f2c53f1f3985/PostgreSQL/Classes/Utils/PGLaunchd.m#L18-L39 and here: https://github.com/MaccaTech/PostgresPrefs/blob/7ad2f9cecb33386a628f90ef3930f2c53f1f3985/PostgreSQL/Classes/Utils/PGProcess.m#L128-L136

But I think Catalina must be more strict about specifying exactly what shell command you're wanting to execute, rather than allowing you to run any shell command. I may have to put in some additional code to tell Catalina I specifically want to run the `launchctl` command. I'll start investigating...

**Comment by mckenfra** [comment]
After re-familiarising myself with the code (it's been a while since I wrote it!) I remember now that there are various operations done by my utils classes [PGFile.m](https://github.com/MaccaTech/PostgresPrefs/blob/7ad2f9cecb33386a628f90ef3930f2c53f1f3985/PostgreSQL/Classes/Utils/PGFile.m), [PGLaunchd.m](https://github.com/MaccaTech/PostgresPrefs/blob/7ad2f9cecb33386a628f90ef3930f2c53f1f3985/PostgreSQL/Classes/Utils/PGLaunchd.m) and [PGProcess.m](https://github.com/MaccaTech/PostgresPrefs/blob/7ad2f9cecb33386a628f90ef3930f2c53f1f3985/PostgreSQL/Classes/Utils/PGProcess.m) that require elevated rights in order to do things like: kill PostgreSQL processes owned by other users, add/remove PostgreSQL `.plist` files from system dirs like `/Library/LaunchAgents` and start/stop PostgreSQL databases by loading/removing launchd agents using `launchctl`. Prior to Catalina, I achieved this by using a [script](https://github.com/MaccaTech/PostgresPrefs/blob/7ad2f9cecb33386a628f90ef3930f2c53f1f3985/PostgreSQL/Scripts/PGPrefsRunAsAdmin.applescript) to run those commands as root, after the user has clicked the lock and entered their password. Unfortunately, it seems with Catalina, even the root user now has restrictions on what it can do. I suspect not only do I need to run as root, but I also need to request additional rights for each specific operation that root performs.

The problems I have are:

(1) Without Catalina, it is going to be pretty much impossible for me to try different things in order to see what works. I can't upgrade to Catalina, because I'm using an old 32-bit version of Photoshop which will not work at all on Catalina. I might explore running my old Photoshop in a VM running an earlier version of macOS, but it's going to take a while for me to set all that up.
(2) I previously explored requesting specific permissions to start/stop databases using `launchctl` (see code comments in [PGLaunchd.m](https://github.com/MaccaTech/PostgresPrefs/blob/7ad2f9cecb33386a628f90ef3930f2c53f1f3985/PostgreSQL/Classes/Utils/PGLaunchd.m#L18-L39)), but the problem is this causes the lock to re-lock after 30 seconds, instead of 5 minutes, which I personally find really annoying. If I'm starting/stopping the database, I don't want to keep having to enter my password all the time. I suspect that there's no way around this, which means I may have to completely redesign `PostgrePrefs` to install a [privileged helper tool](https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/DesigningSecureHelpers/DesigningSecureHelpers.html#//apple_ref/doc/uid/TP40002415-CH2-SW1), which would remove the need for the user to keep clicking the lock and entering their password. The user would only need to enter their password once to install the helper when first opening `PostgrePrefs`. Once installed, the helper could then do everything it needed to without any more password prompts forever after. The main downside of this approach, apart from needing a large rewrite of the code, is that _uninstalling_ `PostgrePrefs` becomes more complicated. I'll need to add a special `Uninstall` button to remove the helper whenever you want to uninstall `PostgrePrefs`. The helper sadly doesn't get uninstalled automatically if you right-click on `PostgrePrefs` and click `Remove`.

Anyway, that's where I am right now. Upshot is, it's prob going to take quite a bit of time to work out a solution, sadly... :thinking: 🙁

**Comment by s12chung** [comment]
I see.... good to know...

**Comment by mckenfra** [comment]
Hi guys,

I've pushed out a new release v2.5 which I believe should fix all the issues with Catalina. I managed to get Catalina running in a virtual machine in the end, and it worked fine, so I didn't need to upgrade my main OS and I can still use my old version of Photoshop! Virtualization is pretty amazing...

Can you give the new v2.5 version a try and let me know you get on? https://github.com/MaccaTech/PostgresPrefs/releases I managed to get it notarized without needing it to be in `.pkg` format - it's now a nice plain `.dmg` file. Hopefully the notarization worked and you won't get Gatekeeper refusing to allow you to install it. Let me know if you have any installation issues!

In the end, I decided against the idea of installing a privileged helper. It keeps the package nice and lightweight (since it's just a single `.prefPane` file) with straightforward uninstall. Also I was a bit worried about possible security issues with having a privileged helper permanently installed, even though it's theoretically supposed to be more secure that way (according to Apple). But my research led me to believe that if you install a helper for your app, then it's possible for other apps to also access that helper. The documentation seems pretty sketchy. So the upshot was, I decided to stick with the existing mechanism where you just keep clicking the lock whenever you want to start/stop a server - it's simple and it works.

**Comment by mckenfra** [comment]
@s12chung @BrianHawley 
Can you let me know if you have any issues with v2.5 on Catalina? If I don't hear from you, I'll assume everything is now working ok and so I'll close this issue. Thanks!

**Comment by s12chung** [comment]
requires a password to start and stop the db, but looks like it works!

**Comment by mckenfra** [comment]
That's great, thanks for confirming. So the new build process and notarization is working!

FYI - `PostgresPrefs` has always required a password to start/stop the database. In some situations this is unavoidable, e.g. if you're starting PostgreSQL as the `postgres` user instead of as the current user; also if you click the `At Boot` or `At Login` button then `PostgresPrefs` has to put a configuration file in directories `/Library/LaunchAgents` or `/Library/LaunchDaemons`, which are password-protected. For these reasons I decided to always require the user to enter a password or click-the-lock for all operations. But I'll see if there's any way to eliminate the password if you're just starting/stopping the database as the current user.

Thanks for testing the new version, I'll close this issue because `PostgresPrefs` is now working on Catalina!

**Comment by s12chung** [comment]
> But I'll see if there's any way to eliminate the password if you're just starting/stopping the database as the current user.

that'd be great. thanks for the quick responses/fixes!
