### ISSUE TITLE
Password is required to start and stop database

### ISSUE THREAD

**Issue by s12chung** [MaccaTech/PostgresPrefs#15]
Just leaving the issue here, as mentioned in #14:

> PostgresPrefs has always required a password to start/stop the database. In some situations this is unavoidable, e.g. if you're starting PostgreSQL as the postgres user instead of as the current user; also if you click the At Boot or At Login button then PostgresPrefs has to put a configuration file in directories /Library/LaunchAgents or /Library/LaunchDaemons, which are password-protected. For these reasons I decided to always require the user to enter a password or click-the-lock for all operations. But I'll see if there's any way to eliminate the password if you're just starting/stopping the database as the current user.

I found that this doesn't require a password: https://github.com/remysaissy/mongodb-macosx-prefspane and it still works. Might be because it's using old code and I installed it ages ago. Not sure if this helps.

**Comment by mckenfra** [comment]
@s12chung 

Thanks a lot for following up on this 😃 👍 

Actually I've just been working on exactly this issue! I've now put out a new release (v2.6) which allows you to start/stop PostgreSQL without a password. Give it a try and let me know if you have any issues: https://github.com/MaccaTech/PostgresPrefs/releases **Note:** you need to remove the old version from System Preferences first.

Even with the new version, in some cases a password prompt is still required: if you are starting PostgreSQL as a different user (e.g. the `postgres` account is used when you install PostgreSQL using the EnterpriseDB installer); or if you have selected the `At Boot` option. In both these cases, `PostgresPrefs` needs to run as root, because it needs to update configuration files in `/Library/LaunchDaemons` and also run start stop commands using `system launchd`.

But if you are running PostgreSQL as the current user, and you've chosen the `Manual` startup option, then you should no longer be prompted for a password!

I was going to put more things into this release. I'd like to add an `Uninstall` menu command. Also I think I can make `PostgresPrefs` give a few more helpful hints, e.g. it could show an error icon if you try to start PostgreSQL on the same port as an already-running instance. But since you've raised this password issue, I'v decided to defer all those other things to the next release.

Also I still think the ultimate solution to avoid a password entirely is to install a Privileged Helper. So I might look into that for v3.0...

Anyway, hopefully v2.6 works ok for you!

**Comment by s12chung** [comment]
tested. this works! what timing 😃 

Think I'm happy with this release. Might even prefer it to making it privileged. Thanks!
