### ISSUE TITLE
Not working for current Postresql version

### ISSUE THREAD

**Issue by gedw99** [MaccaTech/PostgresPrefs#17]
Hey again...

I keep getting this log error

log:

````

2021-03-19 09:44:02.464 CET [10067] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 13.2.
2021-03-19 09:44:12.515 CET [10093] FATAL:  database files are incompatible with server


````

i did:

````


brew install postgresql

brew install postgrespreferencepane

````

**Comment by gedw99** [comment]
ah fixed it with:

brew postgresql-upgrade-database

Weird that the version installed by  ``` brew install postgresql ``` is old.

**Comment by mckenfra** [comment]
Maybe you had previously installed postgresql v11 at some point, and it automatically created a v11 data directory when you installed it. Then when you just now did `brew install postgresql` it installed the latest version (v13.2) but it left the the old v11 data directory unchanged from your previous install. Hence the error, which you fixed by upgrading the data directory to v13 using the `postgresql-upgrade-database` command

**Comment by gedw99** [comment]
makes sense. I was also thinking that.
so not a bug, just a human bug :)
